version: 2
updates:
- package-ecosystem: github-actions
  directory: /.github/workflows
  schedule:
    interval: weekly
    day: tuesday
    time: "12:00"
    timezone: America/New_York
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
    day: tuesday
    time: "12:00"
    timezone: America/New_York
