project_name: hinge

builds:
  -
    binary: hinge
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: hinge
    homepage: "https://github.com/pacoguzman/hinge"
    repository:
      owner: pacoguzman
      name: homebrew-tap
    commit_author:
      name: pacoguzman
      email: pacoguzmanp@gmail.com

checksum:
  name_template: 'checksums.txt'

nfpms:
  - maintainer: Paco Guzman <pacoguzmanp@gmail.com>
    description: Creates and updates your Dependabot config.
    homepage: https://github.com/pacoguzman/hinge
    license: MPL
    formats:
      - deb
      - rpm
