  version: 2.1.2
  hooks:
    - type: pre-commit
      actions:
        - name: "Update all go dependencies to latest"
          exec: go
          args: ["get", "-u", "./..."]
        - name: "Run gofmt to format the code"
          exec: gofmt
          args: ["-s", "-w", "**/*.go"]
        - name: "errcheck: Check that errors are checked"
          exec: errcheck
          args: ["./..."]
        - name: "gocyclo: Check cyclomatic complexities"
          exec: gocyclo
          args: ["."]
    - type: pre-push
      actions:
        - name: "Go Build (Ensure pulled modules do not break the build)"
          exec: go
          args: ["build", "-v"]
        - name: "Add all changed files during the pre-commit stage"
          exec: git
          args: ["add", "."]
